Map<String, String> arabic = {
  'HOME': 'مسكن',
  'HISTORY': 'تاريخ',
  'PROFILE': 'الملف الشخصي',
  'COMPLETE_DELIVERY': 'التسليم الكامل',
  'RETURN_DELIVERY': 'تسليم العودة',
  'ACTIVE_ORDERS': 'أوامر نشطة',
  'SEE_DETAILS': 'انظر التفاصيل',
  'GET_DIRECTION': 'احصل على اتجاه',
  'ORDER_ID': 'رقم التعريف الخاص بالطلب : ',
  'SEE_ORDER_DETAILS': 'انظر تفاصيل الطلب',
  'CONFIRM_DELIVERY': 'تأكيد التوصيل',
  'CUSTOMER': 'عميل',
  'ORDER_DETAILS': 'تفاصيل الطلب',
  'YOUR_ESTIMATE_DELIVERY_TIME': 'وقت التسليم التقديري',
  'PAYMENT_INFO': 'معلومات الدفع',
  'METHOD': 'طريقة : ',
  'STATUS': 'حالة : ',
  'ORDER_SUMMERY': 'ملخص الطلب',
  'SIZE': 'بحجم: ',
  'EXTRAS': 'إضافات: ',
  'ADDON': 'اضافه: ',
  'ORDER_HISTORY': 'تاريخ الطلب',
  "DELIVERY_ADDRESS": "عنوان التسليم",
  'INSTRUCTIONS': 'تعليمات: ',
  'SUBTOTAL': 'المجموع الفرعي',
  'DISCOUNT': 'تخفيض',
  'DELIVERY_CHARGE': 'رسوم التوصيل',
  'TOTAL': 'المجموع',
  'CONFIRM_DELIVERY_ALERT': 'هل أنت متأكد من تأكيد التسليم؟',
  'NO_CANCEL': 'رقم, يلغي',
  'YES_CONFIRM': 'نعم, يتأكد',
  'CASH_ON_DELIVERY': 'الدفع عند الاستلام',
  'ORDER_SUCCESSFULLY_DELIVERED': 'تم تسليم الطلب بنجاح',
  'BACK_TO_HOME': 'العودة إلى المنزل',
  'OPEN': 'فتح',
  'MY_PROFILE': 'ملفي',
  'BRANCH': 'فرع',
  'LOG_OUT': 'تسجيل خروج',
  'CHANGE_PASSWORD': 'غير كلمة السر',
  'CHANGE_LANGUAGE': 'تغيير اللغة',
  'PRIVACY_POLICY': 'سياسة الخصوصية',
  'TERMS_CONDITION': 'الشروط والأحكام',
  'EDIT_PROFILE': 'تعديل الملف الشخصي',
  'FIRST_NAME': 'الاسم الاول',
  'LAST_NAME': 'الكنية',
  'EMAIL': 'البريد الإلكتروني',
  'MOBILE_NUMBER': 'رقم الهاتف المحمول',
  'UPDATE_PROFILE': 'تحديث الملف',
  'OLD_PASSWORD': 'كلمة المرور القديمة',
  'NEW_PASSWORD': 'كلمة السر الجديدة',
  'RETYPE_NEW_PASSWORD': 'أعد كتابة كلمة السر الجديدة',
};
