Map<String, String> bangla = {
  'WELCOME_BACK': 'ফিরে আসার জন্য স্বাগতম',
  'HOME': 'হোম',
  'HISTORY': 'ইতিহাস',
  'PROFILE': 'প্রোফাইল',
  'COMPLETE_DELIVERY': 'সম্পূর্ণ ডেলিভারি',
  'RETURN_DELIVERY': 'রিটার্ন ডেলিভারি',
  'ACTIVE_ORDERS': 'একটিভ অর্ডার',
  'SEE_DETAILS': 'বিস্তারিত দেখুন',
  'GET_DIRECTION': 'দিকনির্দেশ পান',
  'ORDER_ID': 'অর্ডার আইডি : ',
  'SEE_ORDER_DETAILS': 'অর্ডারের বিবরণ দেখুন',
  'CONFIRM_DELIVERY': 'কনফার্ম ডেলিভারি',
  'CUSTOMER': 'কাস্টমার',
  'ORDER_DETAILS': 'আদেশ বিবরণী',
  'YOUR_ESTIMATE_DELIVERY_TIME': 'আপনার আনুমানিক বিতরণ সময়',
  'PAYMENT_INFO': 'পেমেন্ট ইনফো',
  'METHOD': 'মেথড',
  'STATUS': 'স্ট্যাটাস',
  'ORDER_SUMMERY': 'অর্ডার সারাংশ',
  'SIZE': 'সাইজ: ',
  'EXTRAS': 'অতিরিক্ত',
  'ADDON': 'অ্যাডন: ',
  'INSTRUCTIONS': 'নির্দেশনা: ',
  'SUBTOTAL': 'সাবটোটাল',
  'DISCOUNT': 'ডিসকাউন্ট',
  'DELIVERY_CHARGE': 'ডেলিভারি চার্জ',
  'TOTAL': 'টোটাল',
  'CONFIRM_DELIVERY_ALERT': 'আপনি ডেলিভারি নিশ্চিত করতে নিশ্চিত?',
  'NO_CANCEL': 'না, বাতিল করুন',
  'YES_CONFIRM': 'নিশ্চিত করুন',
  'YES_COLLECT': 'সংগ্রহ করুন',
  'CASH_ON_DELIVERY': 'প্রদানোত্তর পরিশোধ',
  'ORDER_SUCCESSFULLY_DELIVERED': 'অর্ডার সফলভাবে বিতরণ করা হয়েছে',
  'BACK_TO_HOME': 'বাড়িতে ফিরে যাও',
  'OPEN': 'খোলা',
  'MY_PROFILE': 'মাই প্রোফাইল',
  'BRANCH': 'শাখা',
  'LOG_OUT': 'লগ আউট',
  'ERROR': 'ত্রুটি',
  'সাফল্য': 'Success',
  'CHANGE_PASSWORD': 'পাসওয়ার্ড পরিবর্তন করুন',
  'CHANGE_LANGUAGE': 'ভাষা পরিবর্তন করুন',
  'TERMS_CONDITION': 'বিধি - নিষেধ এবং শর্তাবলী',
  'PRIVACY_POLICY': 'গোপনীয়তা নীতি',
  'EDIT_PROFILE': 'জীবন বৃত্তান্ত সম্পাদনা',
  'FIRST_NAME': 'নামের প্রথম অংশ',
  'LAST_NAME': 'নামের শেষাংশ',
  'EMAIL': 'ইমেইল',
  'PASSWORD': 'পাসওয়ার্ড',
  'MOBILE_NUMBER': 'মোবাইল নম্বর',
  'UPDATE_PROFILE': 'প্রফাইল হালনাগাদ',
  'OLD_PASSWORD': 'পুরানো পাসওয়ার্ড',
  'NEW_PASSWORD': 'নতুন পাসওয়ার্ড',
  'RETYPE_NEW_PASSWORD': 'নতুন পাসওয়ার্ড পুনরায় টাইপ করুন',
  'DELETE_ACCOUNT': 'আপনার প্রোফাইল মুছুন',
  'PROFILE_UPDATE': 'প্রোফাইল আপডেট',
  'PROFILE_UPDATE_SUCCESSFULLY': 'প্রোফাইল সফলভাবে আপডেট করা হয়েছে',
  'PASSWORD_UPDATE_SUCCESSFULLY': 'পাসওয়ার্ড সফলভাবে আপডেট করা হয়েছে৷',
  'CONFIRM_NEW_PASSWORD': 'নিশ্চিত কর নতুন গোপননম্বর',
  'PLEASE_ENTER_VALID_INPUT': 'বৈধ ইনপুট লিখুন',
  'PRESS_BACK_AGAIN_TO_EXIT': 'প্রস্থান করতে আবার ফিরে টিপুন',
  'REMEMBER_ME': 'আমাকে মনে কর',
  'ORDER_HISTORY': 'অর্ডার ইতিহাস',
  "IMAGE_SHOULD_BE_LESS_THAN_2MB": 'ছবি 2MB এর কম হওয়া উচিত',
  "PROFILE_IMAGE_SAVED_SUCCESSFULLY": 'প্রোফাইল ছবি সফলভাবে সংরক্ষিত হয়েছে৷',
  'SOMETHING_WRONG': 'Stimmt etwas nicht',
  "YOU_HAVE_NO_ORDER_FOR_DELIVERY": "ডেলিভারির জন্য আপনার কোন অর্ডার নেই",
  "WAIT_NOTE":
      "আপনার শাখা ব্যবস্থাপক আপনাকে ডেলিভারির জন্য অর্ডার জমা না দেওয়া পর্যন্ত অপেক্ষা করুন।",
  "YOU_HAVE_NO_ORDER_HISTORY": "আপনার কোন অর্ডার ইতিহাস নেই।",
  "ALL_BRANCH": "সমস্ত শাখা",
  "INSTRUCTION": "নির্দেশ",
  "DELIVERY_ADDRESS": "সরবরাহের ঠিকানা",
  "PAID": "পরিশোধ করা",
  "UNPAID": "অবৈতনিক",
  "PICK_PAY": "পিক অ্যান্ড পে",
  "DO_YOU_COLLECT_PAYMENT": "আপনি কি পেমেন্ট সংগ্রহ করেছেন?",
  "AMOUNT": "পরিমাণ",
  "PLEASE_TYPE_FIRST_NAME": "আপনার প্রথম নাম টাইপ করুন",
  "PLEASE_TYPE_LAST_NAME": "আপনার শেষ নাম টাইপ করুন",
  "PLEASE_TYPE_EMAIL": "আপনার ইমেল টাইপ করুন",
  "PLEASE_TYPE_OLD_PASSWORD": "পুরানো পাসওয়ার্ড টাইপ করুন",
  "PLEASE_TYPE_NEW_PASSWORD": "আপনার নতুন পাসওয়ার্ড টাইপ করুন",
  "PLEASE_RETYPE_PASSWORD": "পাসওয়ার্ড পুনরায় টাইপ করুন",
  "PASSWORD_MUST_BE_SIX": "পাসওয়ার্ড কমপক্ষে 6 অক্ষরের হতে হবে",
  "ENTER_VALID_EMAIL": "সঠিক ইমেইল এড্রেস প্রদান করুন",
  "PLEASE_TYPE_PASSWORD": "পাসওয়ার্ড টাইপ করুন",
  "LOCATION_SERVICE_DENIED": "অবস্থান পরিষেবা অস্বীকার করা হয়!",
  "LOCATION_PERMISSION_NOT_ENABLED": "অবস্থান অনুমতি সক্ষম করা হয় না!",
};
