Map<String, String> english = {
  'WELCOME_BACK': 'Welcome Back',
  'HOME': 'Home',
  'HISTORY': 'History',
  'PROFILE': 'Profile',
  'COMPLETE_DELIVERY': 'Complete Delivery',
  'RETURN_DELIVERY': 'Return Delivery',
  'ACTIVE_ORDERS': 'Active Orders',
  'SEE_DETAILS': 'See Details',
  'GET_DIRECTION': 'Get Direction',
  'ORDER_ID': 'Order Id : ',
  'SEE_ORDER_DETAILS': 'See Order Details',
  'CONFIRM_DELIVERY': 'Confirm Delivery',
  'CUSTOMER': 'Customer',
  'ORDER_DETAILS': 'Order Details',
  'YOUR_ESTIMATE_DELIVERY_TIME': 'Your estimate delivery time',
  'PAYMENT_INFO': 'Payment Info',
  'METHOD': 'Method',
  'STATUS': 'Status',
  'ORDER_SUMMERY': 'Order Summery',
  'EXTRAS': 'Extras',
  'INSTRUCTIONS': 'Instructions: ',
  'SUBTOTAL': 'Subtotal',
  'DISCOUNT': 'Discount',
  'DELIVERY_CHARGE': 'Delivery Charge',
  'TOTAL': 'Total',
  'CONFIRM_DELIVERY_ALERT': 'Are You Sure to Confirm Delivery?',
  'NO_CANCEL': 'No, Cancel',
  'YES_CONFIRM': 'Yes, Confirm',
  'YES_COLLECT': 'Yes, Collect',
  'CASH_ON_DELIVERY': 'Cash On Delivery',
  'ORDER_SUCCESSFULLY_DELIVERED': 'Order Successfully Delivered',
  'BACK_TO_HOME': 'Back to Home',
  'OPEN': 'Open',
  'MY_PROFILE': 'My Profile',
  'BRANCH': 'Branch',
  'LOG_OUT': 'Log Out',
  'ERROR': 'Error',
  'SUCCESS': 'Success',
  'CHANGE_PASSWORD': 'Change Password',
  'CHANGE_LANGUAGE': 'Change Language',
  'TERMS_CONDITION': 'Terms & Condition',
  'PRIVACY_POLICY': 'Privacy Policy',
  'EDIT_PROFILE': 'Edit Profile',
  'FIRST_NAME': 'First Name',
  'LAST_NAME': 'Last Name',
  'EMAIL': 'Email',
  'PASSWORD': 'Password',
  'MOBILE_NUMBER': 'Mobile Number',
  'UPDATE_PROFILE': 'Update Profile',
  'OLD_PASSWORD': 'Old Password',
  'NEW_PASSWORD': 'New Password',
  'RETYPE_NEW_PASSWORD': 'Re Type New Password',
  'DELETE_ACCOUNT': 'Delete account',
  'PROFILE_UPDATE': 'Profile Updated',
  'PROFILE_UPDATE_SUCCESSFULLY': 'Profile Updated Successfully',
  'PASSWORD_UPDATE_SUCCESSFULLY': 'Password Updated Successfully',
  'CONFIRM_NEW_PASSWORD': 'Confirm New Password',
  'PLEASE_ENTER_VALID_INPUT': 'Please enter valid input',
  'PRESS_BACK_AGAIN_TO_EXIT': 'Press back again to exit.',
  'REMEMBER_ME': 'Remember me',
  'ORDER_HISTORY': 'Order History',
  "IMAGE_SHOULD_BE_LESS_THAN_2MB": 'Image should be less than 2MB',
  "PROFILE_IMAGE_SAVED_SUCCESSFULLY": 'Profile image saved successfully',
  'SOMETHING_WRONG': 'Something Wrong',
  "YOU_HAVE_NO_ORDER_FOR_DELIVERY": "You have no order for delivery",
  "WAIT_NOTE":
      "Wait until your branch manager submits the order to you for delivery.",
  "YOU_HAVE_NO_ORDER_HISTORY": "You have no order history",
  "ALL_BRANCH": "All Branch",
  "INSTRUCTION": "Instruction",
  "DELIVERY_ADDRESS": "Delivery Address",
  "PAID": "Paid",
  "UNPAID": "Unpaid",
  "PICK_PAY": "Pick & Pay",
  "DO_YOU_COLLECT_PAYMENT": "Do You Collect Payment?",
  "AMOUNT": "Amount",
  "PLEASE_TYPE_FIRST_NAME": "Please type your first name",
  "PLEASE_TYPE_LAST_NAME": "Please type your last name",
  "PLEASE_TYPE_EMAIL": "Please type your email",
  "PLEASE_TYPE_OLD_PASSWORD": "Please type old password",
  "PLEASE_TYPE_NEW_PASSWORD": "Please type your new password",
  "PLEASE_RETYPE_PASSWORD": "Please retype password",
  "PASSWORD_MUST_BE_SIX": "Password must be at least 6 charecter",
  "ENTER_VALID_EMAIL": "Enter valid email",
  "PLEASE_TYPE_PASSWORD": "Please type password",
  "LOCATION_SERVICE_DENIED": "Location service is denied!",
  "LOCATION_PERMISSION_NOT_ENABLED": "Location permission is not enabled!",
};
